trigger:
- main

pool:
  name: SelfHostedPool

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build and Publish .NET 9 Application'
    steps:
    - checkout: self

    - task: UseDotNet@2
      displayName: 'Setup .NET 9'
      inputs:
        packageType: 'sdk'
        version: '9.0.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - script: |
        dotnet restore
        dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)/PublishedApp
      displayName: 'Restore and Build'

    - task: PublishBuildArtifacts@1
      displayName: 'Upload Build Artifact'
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/PublishedApp'
        artifactName: 'salesapp'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: 'Deploy to IIS on Azure VM'
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Artifact'
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'salesapp'
        downloadPath: '$(Build.ArtifactStagingDirectory)/PublishedApp'

    - task: InstallSSHKey@0
      displayName: 'Install SSH Key'
      inputs:
        knownHostsEntry: $(KNOWN_HOSTS)
        sshPublicKey: $(SSH_PUBLIC_KEY)
        sshKeySecureFile: SSH_PRIVATE_KEY
        sshPassphrase: ''

    - script: |
        ssh vmadmin@20.81.164.12 "echo SSH connection verified!"
      displayName: 'Verify SSH Connection'

    - script: |
        ssh vmadmin@20.81.164.12 "mkdir -p C:/inetpub/wwwroot/SalesApp && mkdir -p C:/inetpub/wwwroot/SalesApp/wwwroot"
      displayName: 'Create Target Directory Structure'

    - script: |
        scp -r $(Build.ArtifactStagingDirectory)/PublishedApp/* vmadmin@20.81.164.12:"C:/inetpub/wwwroot/SalesApp/"
      displayName: 'Deploy Files to IIS wwwroot'

    - script: |
        ssh vmadmin@20.81.164.12 "icacls C:\\inetpub\\wwwroot\\SalesApp /grant IIS_IUSRS:(OI)(CI)F"
      displayName: 'Set Proper Permissions'

    - script: |
        ssh vmadmin@20.81.164.12 "iisreset"
      displayName: 'Restart IIS'
