trigger:
- main  # Trigger the pipeline on commits to the 'main' branch

pool:
  name: 'Default'  # This is your default self-hosted agent pool name

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(Build.ArtifactStagingDirectory)/SalesApp'
  publishDirectory: '$(Build.ArtifactStagingDirectory)/publish'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '9.x'  # .NET 9 SDK
    installationPath: $(Agent.ToolsDirectory)/dotnet

# Use DotNetCoreCLI tasks instead of Restore, Build, and Publish tasks
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.sln'  # Restore all solutions in the repo

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.sln'  # Build all solutions in the repo
    buildConfiguration: $(buildConfiguration)

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/*.sln'  # Publish all solutions in the repo
    publishWebProjects: true
    publishDirectory: $(publishDirectory)
    arguments: '--configuration $(buildConfiguration) --output $(publishDirectory)'

- task: CopyFiles@2
  inputs:
    SourceFolder: $(publishDirectory)
    Contents: '**'
    TargetFolder: $(Build.ArtifactStagingDirectory)/SalesApp

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'SalesApp'
    publishLocation: 'Container'

# Deployment to IIS on Self-hosted Agent VM
- task: AzureCLI@2
  inputs:
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      $ErrorActionPreference = "Stop"
      
      # Set paths
      $sourcePath = "$(Build.ArtifactStagingDirectory)/SalesApp"
      $destinationPath = "C:\inetpub\wwwroot\SalesApp"  # IIS root folder
      
      # Copy files to IIS directory
      Copy-Item -Path $sourcePath\* -Destination $destinationPath -Recurse -Force
      
      # Restart IIS to apply changes
      iisreset

    displayName: 'Deploy to IIS Server on Self-Hosted Agent VM'
