trigger:
- main

# pool:
#   name: 'selfhosted'
 

pool:
  name: "default"

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build and Publish .NET 9 Application'
    steps:
    - checkout: self

    - task: UseDotNet@2
      displayName: 'Setup .NET 9'
      inputs:
        packageType: 'sdk'
        version: '9.0.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - script: |
        dotnet restore
        dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)/PublishedApp
      displayName: 'Restore and Build'

    - task: PublishBuildArtifacts@1
      displayName: 'Upload Build Artifact'
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/PublishedApp'
        artifactName: 'SalesApp'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  jobs:
  - deployment: DeployToIIS
    displayName: 'Deploy to IIS using Deployment Group'
    environment: 'IIS Clasic'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download Artifact'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'SalesApp'
              downloadPath: '$(Build.ArtifactStagingDirectory)/PublishedApp'

          - task: IISWebAppManagementOnMachineGroup@0
            displayName: 'Stop IIS Before Deployment'
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'StopWebsite'
              WebsiteName: 'SalesApp'

          - task: IISWebAppDeploymentOnMachineGroup@0
            displayName: 'Deploy Application to IIS'
            inputs:
              WebSiteName: 'SalesApp'
              Package: '$(Build.ArtifactStagingDirectory)/PublishedApp'
              RemoveAdditionalFilesFlag: true
              TakeAppOfflineFlag: true

          - task: IISWebAppManagementOnMachineGroup@0
            displayName: 'Start IIS After Deployment'
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'StartWebsite'
              WebsiteName: 'SalesApp'
