trigger:
  - main

pool:
  name: SelfHostedPool

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build and Publish .NET 9 Application'
    steps:
    - checkout: self

    - task: UseDotNet@2
      displayName: 'Setup .NET 9'
      inputs:
        packageType: 'sdk'
        version: '9.0.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - script: |
        dotnet restore
        dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)/PublishedApp
      displayName: 'Restore and Build'

    - task: PublishBuildArtifacts@1
      displayName: 'Upload Build Artifact'
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/PublishedApp'
        artifactName: 'PublishedApp'  # Changed artifact name to avoid confusion

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: 'Deploy to IIS on Azure VM'
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Artifact'
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'PublishedApp'  # Using the correct artifact name
        downloadPath: '$(Build.ArtifactStagingDirectory)/PublishedApp'

    - task: InstallSSHKey@0
      displayName: 'Install SSH Key'
      inputs:
        knownHostsEntry: $(KNOWN_HOSTS)
        sshKeySecureFile: 'SSH_PRIVATE_KEY'
        sshPassphrase: ''

    - script: |
        ssh-keyscan -H 20.81.164.12 >> ~/.ssh/known_hosts
        ssh -o BatchMode=yes -v vmadmin@20.81.164.12 "echo SSH connection verified!"
      displayName: 'Verify SSH Connection'

    - script: |
        ssh -o BatchMode=yes vmadmin@20.81.164.12 "powershell -Command \"if (-not (Test-Path 'C:\\inetpub\\wwwroot\\SalesApp')) { New-Item -ItemType Directory -Path 'C:\\inetpub\\wwwroot\\SalesApp' -Force }\""
      displayName: 'Create SalesApp Directory'

    - task: PowerShell@2
      displayName: 'Deploy Files to Correct Location'
      inputs:
        targetType: 'inline'
        script: |
          # 1. Clean target directory
          Write-Host "##[section]Cleaning target directory..."
          ssh -o BatchMode=yes vmadmin@20.81.164.12 "powershell -Command `"Remove-Item 'C:\inetpub\wwwroot\SalesApp\*' -Recurse -Force -ErrorAction SilentlyContinue`""

          # 2. Copy contents of PublishedApp (without adding another subfolder)
          Write-Host "##[section]Copying files to C:\inetpub\wwwroot\SalesApp..."
          $sourcePath = "$(Build.ArtifactStagingDirectory)/PublishedApp"
          Get-ChildItem -Path $sourcePath | ForEach-Object {
              $item = $_
              if ($item.PSIsContainer) {
                  Write-Host "Copying directory: $($item.Name)"
                  scp -r -o BatchMode=yes "$($item.FullName)" vmadmin@20.81.164.12:"C:/inetpub/wwwroot/SalesApp/"
              } else {
                  Write-Host "Copying file: $($item.Name)"
                  scp -o BatchMode=yes "$($item.FullName)" vmadmin@20.81.164.12:"C:/inetpub/wwwroot/SalesApp/"
              }
          }
          Write-Host "##[section]File deployment completed successfully"

    - task: PowerShell@2
      displayName: 'Set Permissions'
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "##[section]Setting permissions..."
          ssh -o BatchMode=yes vmadmin@20.81.164.12 "powershell -Command `"icacls 'C:\inetpub\wwwroot\SalesApp' /grant IIS_IUSRS:(OI)(CI)F /T`""
          ssh -o BatchMode=yes vmadmin@20.81.164.12 "powershell -Command `"icacls 'C:\inetpub\wwwroot\SalesApp' /grant 'NT AUTHORITY\SYSTEM':(OI)(CI)F /T`""

    - script: |
        ssh -o BatchMode=yes vmadmin@20.81.164.12 "iisreset"
      displayName: 'Restart IIS'
