name: Deploy to IIS on Azure VM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@vv

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore and Build
        run: |
          dotnet restore
          dotnet publish -c Release -o PublishedApp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: salesapp
          path: PublishedApp

  deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: salesapp
          path: PublishedApp

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v4
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Deploy to Azure VM via SCP
        run: |
          scp -r -o StrictHostKeyChecking=no PublishedApp/* vmadmin@20.81.164.12:C:/inetpub/salesapp

      - name: Restart IIS
        run: |
          ssh -o StrictHostKeyChecking=no vmadmin@20.81.164.12 "iisreset"
