name: Deploy to IIS on Azure VM

on:
  push:
    branches:
      - main

env:
  VM_IP: 20.81.164.12
  VM_USER: vmadmin
  DEPLOY_PATH: C:/inetpub/salesapp

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore and Build
        run: |
          dotnet restore
          dotnet publish -c Release -o PublishedApp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: salesapp
          path: PublishedApp

  deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: salesapp
          path: PublishedApp

      - name: Setup SSH Infrastructure
        run: |
          # Create .ssh directory
          mkdir -p $env:USERPROFILE\.ssh
          
          # Save private key with proper permissions
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $env:USERPROFILE\.ssh\id_rsa
          icacls $env:USERPROFILE\.ssh\id_rsa /inheritance:r /grant:r "$env:USERNAME:F"
          
          # Add known_hosts entry (from ssh-keyscan)
          echo "20.81.164.12 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP++GxNJb0SrrKhRL0CLJk/UrJ7NWL0Ih9FtM5nHgzbf" > $env:USERPROFILE\.ssh\known_hosts
          
          # Verify setup
          ls $env:USERPROFILE\.ssh
          type $env:USERPROFILE\.ssh\id_rsa
        shell: pwsh

      - name: Verify SSH Connection
        run: |
          ssh -T -v -i $env:USERPROFILE\.ssh\id_rsa -o StrictHostKeyChecking=no ${{ env.VM_USER }}@${{ env.VM_IP }} "echo 'SSH connection verified!'"

      - name: Deploy Application Files
        run: |
          scp -r -v -i $env:USERPROFILE\.ssh\id_rsa -o StrictHostKeyChecking=no PublishedApp/* ${{ env.VM_USER }}@${{ env.VM_IP }}:"${{ env.DEPLOY_PATH }}"

      - name: Restart IIS
        run: |
          ssh -v -i $env:USERPROFILE\.ssh\id_rsa -o StrictHostKeyChecking=no ${{ env.VM_USER }}@${{ env.VM_IP }} "iisreset"
