name: Deploy to IIS on Azure VM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore and Build
        run: |
          dotnet restore
          dotnet publish -c Release -o PublishedApp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: salesapp
          path: PublishedApp

  deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: salesapp
          path: PublishedApp

      - name: List downloaded files (debug)
        run: dir PublishedApp /s
        shell: cmd

      - name: Install SSH key and test connection
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          config: |
            Host azure-vm
              HostName 20.81.164.12
              User vmadmin
              IdentityFile ~/.ssh/id_rsa
              StrictHostKeyChecking no

      - name: Test SSH connection
        run: ssh azure-vm "echo 'SSH connection successful!'"

      - name: Create remote directory (if needed)
        run: ssh azure-vm "mkdir -p C:/inetpub/salesapp"

      - name: Deploy to Azure VM via SCP
        run: scp -v -r PublishedApp/* azure-vm:C:/inetpub/salesapp

      - name: Verify deployment
        run: ssh azure-vm "dir C:/inetpub/salesapp"

      - name: Restart IIS
        run: ssh azure-vm "iisreset"
