name: Deploy to IIS on Azure VM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore and Build
        run: |
          dotnet restore
          dotnet publish -c Release -o PublishedApp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: salesapp
          path: PublishedApp

  deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: salesapp
          path: PublishedApp

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          config: |
            Host azure-vm
              HostName 20.81.164.12
              User vmadmin
              IdentityFile ~/.ssh/id_rsa
              StrictHostKeyChecking no

      - name: Prepare target directory
        run: |
          ssh azure-vm "powershell -Command \"
            if (!(Test-Path C:\\inetpub\\wwwroot\\SalesApp)) {
              New-Item -Path C:\\inetpub\\wwwroot\\SalesApp -ItemType Directory
            }
            Get-ChildItem C:\\inetpub\\wwwroot\\SalesApp | Remove-Item -Recurse -Force
          \""

      - name: Deploy files
        run: scp -rp PublishedApp/* azure-vm:"C:/inetpub/wwwroot/SalesApp/"

      - name: Set permissions
        run: ssh azure-vm "powershell icacls C:\\inetpub\\wwwroot\\SalesApp /grant IIS_IUSRS:(OI)(CI)F /grant 'vmadmin:(OI)(CI)F'"

      - name: Verify deployment
        run: ssh azure-vm "powershell Get-ChildItem C:\\inetpub\\wwwroot\\SalesApp"

      - name: Restart IIS
        run: ssh azure-vm "iisreset"
