name: Deploy to IIS on Azure VM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore and Build
        run: |
          dotnet restore
          dotnet publish -c Release -o PublishedApp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: salesapp
          path: PublishedApp

  deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: salesapp
          path: PublishedApp
  
      - name: Setup SSH directory and known_hosts
        run: |
          $sshPath = "$env:USERPROFILE\.ssh"
          if (!(Test-Path $sshPath)) { New-Item -ItemType Directory -Path $sshPath }
          if (!(Test-Path "$sshPath\known_hosts")) { New-Item -ItemType File -Path "$sshPath\known_hosts" }
          # Set strict permissions
          icacls $sshPath /inheritance:r /grant:r "$env:USERNAME":F
          icacls "$sshPath\known_hosts" /inheritance:r /grant:r "$env:USERNAME":F
        shell: pwsh
  
      - name: Add Azure VM to known_hosts
        run: |
          ssh-keyscan -H 172.191.12.102 >> "$env:USERPROFILE\.ssh\known_hosts"
        shell: bash
  
      - name: Install Win32-OpenSSH (if needed)
        run: |
          Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0
        shell: pwsh
  
      - name: Deploy to Azure VM via SCP
        run: |
          $env:SSH_AUTH_SOCK = "nul"
          scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile="$env:USERPROFILE\.ssh\known_hosts" PublishedApp/* adminuser@172.191.12.102:C:/inetpub/salesapp
        env:
          SSH_PASS: ${{ secrets.SSH_PASSWORD }}
        shell: pwsh
  
      - name: Restart IIS
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile="$env:USERPROFILE\.ssh\known_hosts" adminuser@172.191.12.102 "iisreset"
        env:
          SSH_PASS: ${{ secrets.SSH_PASSWORD }}
        shell: pwsh
