name: Deploy to Azure Windows VM

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          
      - name: Build and Publish
        run: |
          dotnet restore
          dotnet publish -c Release -o published -r win-x64 --self-contained false

      - uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: published

  deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: webapp
          path: published

      - name: Configure PowerShell Remoting
        run: |
          # Trust the target VM (temporarily)
          Set-Item WSMan:\localhost\Client\TrustedHosts -Value "172.191.12.102" -Force
          
          # Test basic connectivity
          Test-NetConnection -ComputerName 172.191.12.102 -Port 5985
        shell: powershell

      - name: Deploy Application
        run: |
          $securePass = ConvertTo-SecureString "${{ secrets.VM_PASSWORD }}" -AsPlainText -Force
          $cred = New-Object System.Management.Automation.PSCredential("adminuser", $securePass)
          
          # Create remote session
          $session = New-PSSession -ComputerName 172.191.12.102 -Credential $cred -Authentication Negotiate
          
          try {
              # Stop IIS
              Invoke-Command -Session $session -ScriptBlock {
                  Stop-Service W3SVC -ErrorAction SilentlyContinue
              }
              
              # Copy files
              Copy-Item -Path "published\*" -Destination "C:\inetpub\salesapp\" -ToSession $session -Recurse -Force
              
              # Restart IIS
              Invoke-Command -Session $session -ScriptBlock {
                  Start-Service W3SVC
                  iisreset
              }
          }
          finally {
              if ($session) { Remove-PSSession $session }
          }
        shell: powershell
