name: Deploy to IIS on Azure VM

on:
  push:
    branches:
      - main

env:
  VM_IP: 20.81.164.12
  VM_USER: vmadmin
  DEPLOY_PATH: C:/inetpub/salesapp

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore and Build
        run: |
          dotnet restore
          dotnet publish -c Release -o PublishedApp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: salesapp
          path: PublishedApp

  deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: salesapp
          path: PublishedApp

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host to known hosts
        run: |
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > $env:USERPROFILE\.ssh\known_hosts
          type $env:USERPROFILE\.ssh\known_hosts

      - name: Test SSH connection
        run: |
          ssh -T -v ${{ env.VM_USER }}@${{ env.VM_IP }} "echo 'SSH connection successful!'"

      - name: Deploy files via SCP
        run: |
          scp -r -v -o ConnectTimeout=30 -o StrictHostKeyChecking=no PublishedApp/* ${{ env.VM_USER }}@${{ env.VM_IP }}:${{ env.DEPLOY_PATH }}

      - name: Restart IIS
        run: |
          ssh -v -o StrictHostKeyChecking=no ${{ env.VM_USER }}@${{ env.VM_IP }} "iisreset"
