name: Deploy to IIS on Azure VM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore and Build
        run: |
          dotnet restore
          dotnet publish -c Release -o PublishedApp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: salesapp
          path: PublishedApp

  deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: salesapp
          path: PublishedApp

      - name: Install SSH key and configure
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          config: |
            Host azure-vm
              HostName 20.81.164.12
              User vmadmin
              IdentityFile ~/.ssh/id_rsa
              StrictHostKeyChecking no

      - name: Verify SSH connection
        run: ssh azure-vm "echo SSH connection verified!"

      - name: Create target directory structure
        run: |
          ssh azure-vm "
          if not exist C:\inetpub\salesapp mkdir C:\inetpub\salesapp
          if not exist C:\inetpub\salesapp\wwwroot mkdir C:\inetpub\salesapp\wwwroot
          "

      - name: Deploy files to wwwroot
        run: scp -r PublishedApp/* azure-vm:"C:/inetpub/salesapp/wwwroot/"

      - name: Set proper permissions
        run: ssh azure-vm "icacls C:\inetpub\salesapp\wwwroot /grant IIS_IUSRS:(OI)(CI)F"

      - name: Restart IIS
        run: ssh azure-vm "iisreset"
