name: Deploy to IIS on Azure VM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore and Build
        run: |
          dotnet restore
          dotnet publish -c Release -o PublishedApp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: salesapp
          path: PublishedApp

  deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: salesapp
          path: PublishedApp
  
      - name: Ensure SSH Directory Exists
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
        shell: bash
  
      - name: Add Azure VM to known_hosts
        run: |
          ssh-keyscan -H 172.191.12.102 >> ~/.ssh/known_hosts
        shell: bash
  
      - name: Install SSH Pass (if needed)
        run: |
          apt-get update
          apt-get install -y sshpass
        if: runner.os == 'Linux'
        shell: bash
  
      - name: Deploy to Azure VM via SCP
        run: |
          sshpass -p "$SSH_PASS" scp -o StrictHostKeyChecking=no -r PublishedApp/* adminuser@172.191.12.102:C:/inetpub/salesapp
        env:
          SSH_PASS: ${{ secrets.SSH_PASSWORD }}
        shell: bash
  
      - name: Restart IIS
        run: |
          sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no adminuser@172.191.12.102 "iisreset"
        env:
          SSH_PASS: ${{ secrets.SSH_PASSWORD }}
        shell: bash
